version: "3"

services:
  hello-backend-service:
    image: bilec/hello-backend-webapp
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  ktor-microservice:
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile
    environment:
      - GREET_BACKEND_SERVICE_HOST=hello-backend-service
      - GREET_BACKEND_SERVICE_PORT=8081
    ports:
      - "8082:8080"